name: tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        deno-version: ["v1.x", "nightly"]

    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Setup Deno ${{ matrix.deno-version }}
        with:
          deno-version: ${{ matrix.deno-version }}
        uses: denolib/setup-deno@v2

      - name: Run Tests
        run: deno test -A
